# Generated by Django 4.1.3 on 2022-12-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_todo_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notepad',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
