# Generated by Django 4.1.3 on 2022-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_notepad_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepad',
            name='host',
        ),
        migrations.AlterField(
            model_name='notepad',
            name='body',
            field=models.TextField(),
        ),
    ]
